# SPDX-FileCopyrightText: 2020 pukkamustard <pukkamustard@posteo.net>
#
# SPDX-License-Identifier: CC0-1.0

# GitLab CI configuration

image: elixir:latest

stages:
  - test

test:
  stage: test
  variables:
    MIX_ENV: test
  before_script:
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get
  script:
    - mix check

# pages:
#   script:
#     - mix docs
#   artifacts:
#     paths:
#       - docs
#   only:
#     - master
