#+TITLE: CPub

A semantic ActivityPub server.

* About

CPub is a general [[https://www.w3.org/TR/activitypub/][ActivityPub]] server built upon Semantic Web ideas. Most notably it also implements a [[https://www.w3.org/TR/ldp/][Linked Data Platform (LDP)]] and uses [[https://www.w3.org/TR/turtle/][RDF Turtle]] as serialization for data.

The project goals are:

- Develop a general ActivityPub server that can be used to create any kind of structured content.
- Experiment with using Linked Data (RDF) as data model for everything.

CPub is developed as part of the [[https://miaengiadina.github.io/openengiadina/][openEngiadina]] platform for open local knowledge. Development is supported by [[https://www.miaengiadina.ch/][miaEngiadina]].

* Quick start

To start the CPub server:

  * Install dependencies with `mix deps.get`
  * Create and migrate your database with `mix ecto.setup`
  * Start Phoenix endpoint with `mix phx.server`

Now you can visit [`localhost:4000`](http://localhost:4000) from your browser.

* Example
** Create a User

Users can be created from the Elixir shell.

For example we create the user "alice" with password "123":

#+BEGIN_SRC elixir
CPub.Users.create_user(username: "alice", password: "123")
#+END_SRC

This creates the user, an actor profile, inbox and outbox for the user and inserts it into the database in a transaction.

Currently public access is not implemented and we need to authenticate to the system. We can do this with HTTP Basic Authentication. We base64 encode the string ~alice:123~ and add it as a header to our HTTP requests:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/users/alice
Accept: text/turtle
Authorization: Basic YWxpY2U6MTIz
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/users/alice>
    a as:Person ;
    as:outbox <http://localhost:4000/users/alice/outbox> ;
    ldp:inbox <http://localhost:4000/users/alice/inbox> .

// GET http://localhost:4000/users/alice
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 437
// content-type: text/turtle; charset=utf-8
// date: Mon, 13 Jan 2020 15:15:42 GMT
// server: Cowboy
// x-request-id: Fel7JOoLJbmDHVwAAAAC
// Request duration: 0.638511s
#+END_SRC

An inbox and outbox has been created for the actor. Both can be accessed:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/users/alice/inbox
Accept: text/turtle
Authorization: Basic YWxpY2U6MTIz
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/users/alice/inbox>
    a ldp:BasicContainer .

// GET http://localhost:4000/users/alice/inbox
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 335
// content-type: text/turtle; charset=utf-8
// date: Mon, 13 Jan 2020 15:15:47 GMT
// server: Cowboy
// x-request-id: Fel7Jh_ckpFziTwAAABi
// Request duration: 0.368419s
#+END_SRC

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/users/alice/inbox
Accept: text/turtle
Authorization: Basic YWxpY2U6MTIz
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/users/alice/inbox>
    a ldp:BasicContainer .

// GET http://localhost:4000/users/alice/inbox
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 335
// content-type: text/turtle; charset=utf-8
// date: Mon, 13 Jan 2020 15:15:52 GMT
// server: Cowboy
// x-request-id: Fel7J0FvaO4j5J0AAACC
// Request duration: 0.363593s
#+END_SRC

Note that currently the inbox and outbox are Linked Data Platform basic containers and not ActivityStreams Collections. In the future they will be both.

** Posting an Activity

We create another user ~bob~:

#+BEGIN_SRC elixir
CPub.Users.create_user(username: "bob", password: "123")
#+END_SRC

As before an inbox and outbox was created for Bob:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/users/bob/inbox
Accept: text/turtle
Authorization: Basic Ym9iOjEyMw==
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/users/bob/inbox>
    a ldp:BasicContainer .

// GET http://localhost:4000/users/bob/inbox
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 333
// content-type: text/turtle; charset=utf-8
// date: Mon, 13 Jan 2020 15:16:02 GMT
// server: Cowboy
// x-request-id: Fel7Kax8ePHlaOIAAACi
// Request duration: 0.367809s
#+END_SRC

Now Alice can post a note to Bob:

#+BEGIN_SRC restclient :exports both
POST http://localhost:4000/users/alice/outbox
Authorization: Basic YWxpY2U6MTIz
Accept: text/turtle
Content-type: text/turtle

@prefix as: <http://www.w3.org/ns/activitystreams#> .

<>
    a as:Create ;
    as:to <http://localhost:4000/users/bob> ;
    as:object _:object .

_:object
    a as:Note ;
    as:content "Good day!"@en ;
    as:content "Guten Tag!"@de ;
    as:content "Grüezi"@gsw ;
    as:content "Bun di!"@roh .
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
// POST http://localhost:4000/users/alice/outbox
// HTTP/1.1 201 Created
// Location: http://localhost:4000/activities/fa1db1ed-8a6a-43b4-97dc-1358fbb5622d
// cache-control: max-age=0, private, must-revalidate
// content-length: 0
// date: Mon, 13 Jan 2020 15:16:14 GMT
// server: Cowboy
// x-request-id: Fel7LGEXC5UXSm0AAADC
// Request duration: 0.394329s
#+END_SRC

The activity has been created and can be accessed:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/activities/fa1db1ed-8a6a-43b4-97dc-1358fbb5622d
Authorization: Basic YWxpY2U6MTIz
Accept: text/turtle
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/activities/fa1db1ed-8a6a-43b4-97dc-1358fbb5622d>
    a as:Create ;
    as:actor <http://localhost:4000/users/alice> ;
    as:object <http://localhost:4000/objects/3fc8e8b6-5d25-4978-86e2-b13175e95c77> ;
    as:to <http://localhost:4000/users/bob> .

// GET http://localhost:4000/activities/fa1db1ed-8a6a-43b4-97dc-1358fbb5622d
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 538
// content-type: text/turtle; charset=utf-8
// date: Mon, 13 Jan 2020 15:17:10 GMT
// server: Cowboy
// x-request-id: Fel7OVj8X-5DpVUAAAEC
// Request duration: 0.362603s
#+END_SRC

The object has received an id for itself and can be accessed directly:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/objects/3fc8e8b6-5d25-4978-86e2-b13175e95c77
Authorization: Basic YWxpY2U6MTIz
Accept: text/turtle
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/objects/3fc8e8b6-5d25-4978-86e2-b13175e95c77>
    a as:Note ;
    as:content "Guten Tag!"@de, "Good day!"@en, "Grüezi"@gsw, "Bun di!"@roh .

// GET http://localhost:4000/objects/3fc8e8b6-5d25-4978-86e2-b13175e95c77
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 430
// content-type: text/turtle; charset=utf-8
// date: Mon, 13 Jan 2020 15:17:23 GMT
// server: Cowboy
// x-request-id: Fel7PGbVge-3k_sAAAFC
// Request duration: 0.368027s
#+END_SRC

We uses Alice's credentials (encoded as ~YWxpY2U6MTIz~) to get the activity and object, but we could also use Bob's. Bob has been given read access to the created activity and object:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/activities/fa1db1ed-8a6a-43b4-97dc-1358fbb5622d
Authorization: Basic Ym9iOjEyMw==
Accept: text/turtle
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/activities/fa1db1ed-8a6a-43b4-97dc-1358fbb5622d>
    a as:Create ;
    as:actor <http://localhost:4000/users/alice> ;
    as:object <http://localhost:4000/objects/3fc8e8b6-5d25-4978-86e2-b13175e95c77> ;
    as:to <http://localhost:4000/users/bob> .

// GET http://localhost:4000/activities/fa1db1ed-8a6a-43b4-97dc-1358fbb5622d
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 538
// content-type: text/turtle; charset=utf-8
// date: Mon, 13 Jan 2020 15:17:40 GMT
// server: Cowboy
// x-request-id: Fel7QIk12z1GHC4AAAFi
// Request duration: 0.365966s
#+END_SRC

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/objects/3fc8e8b6-5d25-4978-86e2-b13175e95c77
Authorization: Basic Ym9iOjEyMw==
Accept: text/turtle
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/objects/3fc8e8b6-5d25-4978-86e2-b13175e95c77>
    a as:Note ;
    as:content "Guten Tag!"@de, "Good day!"@en, "Grüezi"@gsw, "Bun di!"@roh .

// GET http://localhost:4000/objects/3fc8e8b6-5d25-4978-86e2-b13175e95c77
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 430
// content-type: text/turtle; charset=utf-8
// date: Mon, 13 Jan 2020 15:18:17 GMT
// server: Cowboy
// x-request-id: Fel7SPsjb0rCC4oAAAHh
// Request duration: 0.364123s
#+END_SRC

The activity has also been placed in the Alice's outbox:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/users/alice/outbox
Authorization: Basic YWxpY2U6MTIz
Accept: text/turtle
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/users/alice/outbox>
    a ldp:BasicContainer ;
    ldp:contains <http://localhost:4000/activities/fa1db1ed-8a6a-43b4-97dc-1358fbb5622d> .

// GET http://localhost:4000/users/alice/outbox
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 427
// content-type: text/turtle; charset=utf-8
// date: Mon, 13 Jan 2020 15:18:33 GMT
// server: Cowboy
// x-request-id: Fel7TOS9zjxdOyEAAAIB
// Request duration: 0.363977s
#+END_SRC

And in Bob's inbox:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/users/bob/inbox
Authorization: Basic Ym9iOjEyMw==
Accept: text/turtle
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/users/bob/inbox>
    a ldp:BasicContainer ;
    ldp:contains <http://localhost:4000/activities/fa1db1ed-8a6a-43b4-97dc-1358fbb5622d> .

// GET http://localhost:4000/users/bob/inbox
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 424
// content-type: text/turtle; charset=utf-8
// date: Mon, 13 Jan 2020 15:19:10 GMT
// server: Cowboy
// x-request-id: Fel7VVi4tf7luDMAAAIh
// Request duration: 0.360935s
#+END_SRC
** Generality

CPub has an understanding of what activities are (as defined in ActivityStreams) and uses this understanding to figure out what to do when you post something to an outbox.

Other than that, CPub is completely oblivious to what kind of data you create, share or link to (as long as it is RDF).
*** Event

For example we can create an event instead of a note (using the schema.org vocabulary):

#+BEGIN_SRC restclient :exports both
POST http://localhost:4000/users/alice/outbox
Authorization: Basic YWxpY2U6MTIz
Accept: text/turtle
Content-type: text/turtle

@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema> .

<>
    a as:Create ;
    as:to <http://localhost:4000/users/bob> ;
    as:object _:object .

_:object
    a schema:Event ;
    schema:name "My super cool event" ;
    schema:url "http://website-to-my-event" ;
    schema:startDate "2020-01-31T00:00:00+01:00"^^xsd:date ;
    schema:endDate "2020-02-02T00:00:00+01:00"^^xsd:date .

#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
// POST http://localhost:4000/users/alice/outbox
// HTTP/1.1 201 Created
// Location: http://localhost:4000/activities/d778c801-c690-4839-b76a-7bb327262b8f
// access-control-allow-credentials: true
// access-control-allow-origin: *
// access-control-expose-headers: 
// cache-control: max-age=0, private, must-revalidate
// content-length: 0
// date: Wed, 29 Jan 2020 15:55:53 GMT
// server: Cowboy
// x-request-id: Fe5HlD4n5wuqDHQAAEgB
// Request duration: 0.385480s
#+END_SRC

The activity:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/activities/d778c801-c690-4839-b76a-7bb327262b8f
Authorization: Basic YWxpY2U6MTIz
Accept: text/turtle
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/activities/d778c801-c690-4839-b76a-7bb327262b8f>
    a as:Create ;
    as:actor <http://localhost:4000/users/alice> ;
    as:object <http://localhost:4000/objects/d6da85d4-d3fd-4ae9-b079-851594100dbf> ;
    as:to <http://localhost:4000/users/bob> .

// GET http://localhost:4000/activities/d778c801-c690-4839-b76a-7bb327262b8f
// HTTP/1.1 200 OK
// access-control-allow-credentials: true
// access-control-allow-origin: *
// access-control-expose-headers: 
// cache-control: max-age=0, private, must-revalidate
// content-length: 538
// content-type: text/turtle; charset=utf-8
// date: Wed, 29 Jan 2020 15:57:10 GMT
// server: Cowboy
// x-request-id: Fe5HplY91yG0IdEAAEhB
// Request duration: 0.375856s
#+END_SRC

And the object (our event!) has got it's own id:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/objects/d6da85d4-d3fd-4ae9-b079-851594100dbf
Authorization: Basic YWxpY2U6MTIz
Accept: text/turtle
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/objects/d6da85d4-d3fd-4ae9-b079-851594100dbf>
    a <http://schema.org/Event> ;
    <http://schema.org/endDate> "2020-02-02T00:00:00+01:00"^^<http://www.w3.org/2001/XMLSchemadate> ;
    <http://schema.org/name> "My super cool event" ;
    <http://schema.org/startDate> "2020-01-31T00:00:00+01:00"^^<http://www.w3.org/2001/XMLSchemadate> ;
    <http://schema.org/url> "http://website-to-my-event" .

// GET http://localhost:4000/objects/d6da85d4-d3fd-4ae9-b079-851594100dbf
// HTTP/1.1 200 OK
// access-control-allow-credentials: true
// access-control-allow-origin: *
// access-control-expose-headers: 
// cache-control: max-age=0, private, must-revalidate
// content-length: 687
// content-type: text/turtle; charset=utf-8
// date: Wed, 29 Jan 2020 15:58:06 GMT
// server: Cowboy
// x-request-id: Fe5Hs71KVA0TUrIAAEhh
// Request duration: 0.372090s
#+END_SRC

The event can be commented on, liked or shared, like any other ActivityPub object.

*** Geo data

It is also possible to post geospatial data. For example a geo-tagged note:

#+BEGIN_SRC restclient :exports both
POST http://localhost:4000/users/alice/outbox
Authorization: Basic YWxpY2U6MTIz
Accept: text/turtle
Content-type: text/turtle

@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#> .

<>
    a as:Create ;
    as:to <http://localhost:4000/users/bob> ;
    as:object _:object .

_:object
    a as:Note ;
    as:content "The water here is amazing!"@en ;
    geo:lat 46.794932821448725 ;
    geo:long 10.300304889678957 .

#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
// POST http://localhost:4000/users/alice/outbox
// HTTP/1.1 201 Created
// Location: http://localhost:4000/activities/5619343f-cefd-4d01-beed-b5147422b01c
// access-control-allow-credentials: true
// access-control-allow-origin: *
// access-control-expose-headers: 
// cache-control: max-age=0, private, must-revalidate
// content-length: 0
// date: Wed, 29 Jan 2020 16:08:00 GMT
// server: Cowboy
// x-request-id: Fe5IP1jD5ufXnUEAAEjB
// Request duration: 0.386719s
#+END_SRC

A geo-tagged note has been created:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/objects/4ba93119-b210-4f6f-aab6-db9a3124c73b
Authorization: Basic YWxpY2U6MTIz
Accept: text/turtle
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/objects/4ba93119-b210-4f6f-aab6-db9a3124c73b>
    a as:Note ;
    <http://www.w3.org/2003/01/geo/wgs84_pos#lat> 46.794932821448725 ;
    <http://www.w3.org/2003/01/geo/wgs84_pos#long> 10.300304889678957 ;
    as:content "The water here is amazing!"@en .

// GET http://localhost:4000/objects/4ba93119-b210-4f6f-aab6-db9a3124c73b
// HTTP/1.1 200 OK
// access-control-allow-credentials: true
// access-control-allow-origin: *
// access-control-expose-headers: 
// cache-control: max-age=0, private, must-revalidate
// content-length: 543
// content-type: text/turtle; charset=utf-8
// date: Wed, 29 Jan 2020 16:09:02 GMT
// server: Cowboy
// x-request-id: Fe5ITewk2M_dR4QAAEkB
// Request duration: 0.372565s
#+END_SRC

A client that understands what ~geo:lat~ and ~geo:long~ means could show this note on a map. See also https://github.com/miaEngiadina/geopub.
