#+TITLE: CPub

A semantic ActivityPub server.

* About

CPub is a general [[https://www.w3.org/TR/activitypub/][ActivityPub]] server built upon Semantic Web ideas. Most notably it also implements a [[https://www.w3.org/TR/ldp/][Linked Data Platform (LDP)]] and uses [[https://www.w3.org/TR/turtle/][RDF Turtle]] as serialization for data.

The project goals are:

- Develop a general ActivityPub server that can be used to create any kind of structured content.
- Experiment with using Linked Data (RDF) as data model for everything.

CPub is developed as part of the [[https://miaengiadina.github.io/openengiadina/][openEngiadina]] platform for open local knowledge. Development is supported by [[https://www.miaengiadina.ch/][miaEngiadina]].

* Quick start

To start the CPub server:

  * Install dependencies with `mix deps.get`
  * Create and migrate your database with `mix ecto.setup`
  * Start Phoenix endpoint with `mix phx.server`

Now you can visit [`localhost:4000`](http://localhost:4000) from your browser.

* Example
** Create an Actor

An Actor can be created with a ~POST~ request to ~/actors~. We create an actor "Alyssa":

#+BEGIN_SRC restclient :exports both
POST http://localhost:4000/actors
Accept: text/turtle
Content-type: text/turtle

@prefix as: <http://www.w3.org/ns/activitystreams#> .

<>
   a as:Person;
   as:name "Alyssa" .
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
// POST http://localhost:4000/actors
// HTTP/1.1 201 Created
// Location: http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc
// cache-control: max-age=0, private, must-revalidate
// content-length: 0
// date: Thu, 19 Dec 2019 11:35:15 GMT
// server: Cowboy
// x-request-id: FeHCmy5CxrwKLiIAAAAE
// Request duration: 0.203247s
#+END_SRC

The server responds with ~201 Created~. The Actor can be retrieved by accessing the URL in the ~Location~ header:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc
Accept: text/turtle
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc>
    a as:Person ;
    as:name "Alyssa" ;
    as:outbox <http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc/outbox> ;
    ldp:inbox <http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc/inbox> .

// GET http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 556
// content-type: text/turtle; charset=utf-8
// date: Thu, 19 Dec 2019 11:35:39 GMT
// server: Cowboy
// x-request-id: FeHCoMNNnrUtaSkAAAAC
// Request duration: 0.036042s
#+END_SRC

An inbox and outbox has been created for the actor. Both can be accessed:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc/inbox
Accept: text/turtle
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc/inbox>
    a ldp:BasicContainer .

// GET http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc/inbox
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 367
// content-type: text/turtle; charset=utf-8
// date: Thu, 19 Dec 2019 11:35:51 GMT
// server: Cowboy
// x-request-id: FeHCo5rU-wOiv94AAABC
// Request duration: 0.008739s
#+END_SRC

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc/outbox
Accept: text/turtle
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc/outbox>
    a ldp:BasicContainer .

// GET http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc/outbox
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 368
// content-type: text/turtle; charset=utf-8
// date: Thu, 19 Dec 2019 11:36:12 GMT
// server: Cowboy
// x-request-id: FeHCqI4hlRzlaOIAAACC
// Request duration: 0.008608s
#+END_SRC

Note that currently the inbox and outbox are Linked Data Platform basic containers and not ActivityStreams Collections. In the future they will be both.
** Posting an Activity

#+BEGIN_SRC restclient :exports both
POST http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc/outbox
Accept: text/turtle
Content-type: text/turtle

@prefix as: <http://www.w3.org/ns/activitystreams#> .

<>
    a as:Create ;
    as:actor <http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc> ;
    as:object _:object .

_:object
    a as:Note ;
    as:content "Good day!"@en ;
    as:content "Guten Tag!"@de ;
    as:content "Grüezi"@gsw ;
    as:content "Bun di!"@roh .
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
// POST http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc/outbox
// HTTP/1.1 201 Created
// Location: http://localhost:4000/objects/43503e2f-732a-4114-b89f-b9b82a5b6cab
// cache-control: max-age=0, private, must-revalidate
// content-length: 0
// date: Thu, 19 Dec 2019 11:37:53 GMT
// server: Cowboy
// x-request-id: FeHCv_gM4vkgF7IAAADi
// Request duration: 0.031898s
#+END_SRC

The activity has been created and can be accessed:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/objects/43503e2f-732a-4114-b89f-b9b82a5b6cab
Accept: text/turtle
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/objects/43503e2f-732a-4114-b89f-b9b82a5b6cab>
    a as:Create ;
    as:actor <http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc> ;
    as:object <http://localhost:4000/objects/d695695c-c9a5-4426-a47b-df8544cf8e68> .

// GET http://localhost:4000/objects/43503e2f-732a-4114-b89f-b9b82a5b6cab
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 521
// content-type: text/turtle; charset=utf-8
// date: Thu, 19 Dec 2019 11:38:44 GMT
// server: Cowboy
// x-request-id: FeHCy4tdXw63k_sAAAEi
// Request duration: 0.008888s
#+END_SRC

Note that the object has received an id for itself and can be accessed directly:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/objects/d695695c-c9a5-4426-a47b-df8544cf8e68
Accept: text/turtle
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/objects/d695695c-c9a5-4426-a47b-df8544cf8e68>
    a as:Note ;
    as:content "Guten Tag!"@de, "Good day!"@en, "Grüezi"@gsw, "Bun di!"@roh .

// GET http://localhost:4000/objects/d695695c-c9a5-4426-a47b-df8544cf8e68
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 430
// content-type: text/turtle; charset=utf-8
// date: Thu, 19 Dec 2019 11:40:03 GMT
// server: Cowboy
// x-request-id: FeHC3fvJbMtGHC4AAAFC
// Request duration: 0.013231s
#+END_SRC

The activity has also been placed in the actor's outbox:

#+BEGIN_SRC restclient :exports both
GET http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc/outbox
Accept: text/turtle
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .

<http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc/outbox>
    a ldp:BasicContainer ;
    ldp:contains <http://localhost:4000/objects/43503e2f-732a-4114-b89f-b9b82a5b6cab> .

// GET http://localhost:4000/actors/dd01f570-5ad0-44e5-9cb6-4f0df8a1d6dc/outbox
// HTTP/1.1 200 OK
// cache-control: max-age=0, private, must-revalidate
// content-length: 456
// content-type: text/turtle; charset=utf-8
// date: Thu, 19 Dec 2019 11:40:42 GMT
// server: Cowboy
// x-request-id: FeHC5zAf6RLCC4oAAAFi
// Request duration: 0.008637s
#+END_SRC
