#!/bin/bash

tmp_output="/tmp/.doctor_output"

function run() {
  echo -n "Running '${1}' ... "

  output=$(${1} 2> /dev/null)

  if [ $? -eq 0 ]
  then
    printf '\033[32m[OK]\033[0m\n'
  else
    if [ -z "$2" ]
    then
      printf '\033[31m[FAIL]\033[0m\n'
      printf '\033[31m%s\033[0m\n' "$output"
    else
      printf '\033[33m[CHANGE]\033[0m\n'
      eval $2
    fi
  fi
}

function mix_coveralls() {
  CMD="MIX_ENV=test mix coveralls.html"
  echo -n "Running '${CMD}' ... "
  eval "bash -c \"${CMD} | grep -E -i 'TOTAL'\" > ${tmp_output}"
  printf '\033[32m[OK]\033[0m\n'
  cat $tmp_output
}

run "mix deps.get"
run "mix format --check-formatted" "mix format"
run "mix credo --strict"
mix_coveralls
run "mix test"
run "mix dialyzer"
